import type { ExerciseMedia, TrainingEnvironment } from "./types";

export const exerciseLibrary: ExerciseMedia[] = [
  {
    id: "warmup-march",
    name: "原地高抬腿热身",
    category: "warmup",
    difficulty: "beginner",
    muscles: ["髋屈肌", "核心", "心肺"],
    environment: "both",
    equipment: [],
    imageUrl: "/media/exercises/warmup-march.svg",
    videoUrl: "https://example.com/videos/warmup-march",
    steps: ["身体站直，双脚与髋同宽", "交替抬膝至舒适高度", "摆臂配合呼吸，保持节奏稳定"],
    cues: ["脚掌轻落地", "上身保持直立", "膝盖不需要追求过高"],
    commonMistakes: ["身体后仰", "落地过重", "憋气"],
    alternatives: ["快走热身", "开合步"],
    contraindications: ["急性膝踝疼痛时降低抬腿高度"],
  },
  {
    id: "bodyweight-squat",
    name: "徒手深蹲",
    category: "strength",
    difficulty: "beginner",
    muscles: ["股四头肌", "臀大肌", "核心"],
    environment: "both",
    equipment: [],
    imageUrl: "/media/exercises/bodyweight-squat.svg",
    videoUrl: "https://example.com/videos/bodyweight-squat",
    steps: ["双脚略宽于肩，脚尖自然外展", "髋部向后坐，膝盖跟随脚尖方向", "下蹲到舒适深度后用脚跟发力站起"],
    cues: ["背部保持自然挺直", "膝盖不要内扣", "动作全程可控"],
    commonMistakes: ["膝盖内扣", "弯腰塌背", "速度过快"],
    alternatives: ["坐椅深蹲", "臀桥"],
    contraindications: ["急性膝痛时优先替换为臀桥或髋主导动作"],
  },
  {
    id: "glute-bridge",
    name: "臀桥",
    category: "strength",
    difficulty: "beginner",
    muscles: ["臀大肌", "腘绳肌", "核心"],
    environment: "both",
    equipment: ["瑜伽垫"],
    imageUrl: "/media/exercises/glute-bridge.svg",
    videoUrl: "https://example.com/videos/glute-bridge",
    steps: ["仰卧屈膝，双脚踩稳地面", "收紧腹部和臀部，抬起髋部", "身体从肩到膝形成直线后缓慢落下"],
    cues: ["发力点在臀部", "腰部不过度反弓", "顶端停留一秒"],
    commonMistakes: ["用腰顶起", "膝盖外翻或内扣", "下降过快"],
    alternatives: ["弹力带臀桥", "罗马尼亚硬拉"],
    contraindications: ["腰椎急性疼痛时暂停"],
  },
  {
    id: "incline-push-up",
    name: "上斜俯卧撑",
    category: "strength",
    difficulty: "beginner",
    muscles: ["胸肌", "肱三头肌", "核心"],
    environment: "both",
    equipment: ["椅子", "桌沿"],
    imageUrl: "/media/exercises/incline-push-up.svg",
    videoUrl: "https://example.com/videos/incline-push-up",
    steps: ["双手撑在稳定平面，身体成直线", "弯肘让胸口靠近支撑面", "推回起始位置"],
    cues: ["肩胛稳定", "肘部约 45 度", "核心收紧"],
    commonMistakes: ["塌腰", "耸肩", "肘部完全外展"],
    alternatives: ["跪姿俯卧撑", "墙壁俯卧撑"],
    contraindications: ["腕部或肩部急性疼痛时暂停"],
  },
  {
    id: "dumbbell-row",
    name: "哑铃划船",
    category: "strength",
    difficulty: "beginner",
    muscles: ["背阔肌", "菱形肌", "肱二头肌"],
    environment: "both",
    equipment: ["哑铃"],
    imageUrl: "/media/exercises/dumbbell-row.svg",
    videoUrl: "https://example.com/videos/dumbbell-row",
    steps: ["一手扶稳支撑物，背部保持平直", "另一手握哑铃向髋部方向拉", "肩胛向后收，再控制下放"],
    cues: ["先收肩胛再拉肘", "不要耸肩", "躯干保持稳定"],
    commonMistakes: ["借力甩动", "圆背", "只用手臂拉"],
    alternatives: ["弹力带划船", "坐姿划船器"],
    contraindications: ["腰背急性疼痛时降低重量或暂停"],
  },
  {
    id: "plank",
    name: "平板支撑",
    category: "strength",
    difficulty: "beginner",
    muscles: ["核心", "肩部", "臀部"],
    environment: "both",
    equipment: ["瑜伽垫"],
    imageUrl: "/media/exercises/plank.svg",
    videoUrl: "https://example.com/videos/plank",
    steps: ["前臂撑地，双脚向后伸直", "收紧腹部和臀部", "保持身体从头到脚成直线"],
    cues: ["不要塌腰", "自然呼吸", "宁可缩短时间也保持标准"],
    commonMistakes: ["臀部过高", "腰部下沉", "憋气"],
    alternatives: ["跪姿平板", "死虫式"],
    contraindications: ["肩腕疼痛时改为死虫式"],
  },
  {
    id: "treadmill-walk",
    name: "跑步机快走",
    category: "cardio",
    difficulty: "beginner",
    muscles: ["心肺", "下肢"],
    environment: "gym",
    equipment: ["跑步机"],
    imageUrl: "/media/exercises/treadmill-walk.svg",
    videoUrl: "https://example.com/videos/treadmill-walk",
    steps: ["从低速开始 3 分钟", "逐步增加到能说短句的强度", "结束前降速放松"],
    cues: ["不要扶把借力", "步幅自然", "保持呼吸稳定"],
    commonMistakes: ["速度上升太快", "低头看脚", "突然停止"],
    alternatives: ["椭圆机", "户外快走"],
    contraindications: ["头晕或胸闷时立即停止并寻求帮助"],
  },
  {
    id: "lat-pulldown",
    name: "高位下拉",
    category: "strength",
    difficulty: "beginner",
    muscles: ["背阔肌", "肱二头肌", "肩胛稳定肌"],
    environment: "gym",
    equipment: ["高位下拉器"],
    imageUrl: "/media/exercises/lat-pulldown.svg",
    videoUrl: "https://example.com/videos/lat-pulldown",
    steps: ["坐稳并固定大腿", "握杆略宽于肩", "将杆拉向上胸，再控制还原"],
    cues: ["胸口微挺", "肩胛先下沉", "不要拉到颈后"],
    commonMistakes: ["身体后仰过多", "耸肩", "下放失控"],
    alternatives: ["弹力带下拉", "哑铃划船"],
    contraindications: ["肩部疼痛时降低重量或替换"],
  },
  {
    id: "stretch-full-body",
    name: "全身拉伸放松",
    category: "mobility",
    difficulty: "beginner",
    muscles: ["髋部", "胸椎", "肩颈", "小腿"],
    environment: "both",
    equipment: ["瑜伽垫"],
    imageUrl: "/media/exercises/stretch-full-body.svg",
    videoUrl: "https://example.com/videos/stretch-full-body",
    steps: ["依次放松小腿、大腿前侧、臀部、胸肩", "每个位置停留 20 到 30 秒", "保持轻微拉伸感，不追求疼痛"],
    cues: ["自然呼吸", "动作缓慢", "疼痛时立即减小幅度"],
    commonMistakes: ["拉伸到疼痛", "弹震式拉伸", "憋气"],
    alternatives: ["泡沫轴放松", "低强度瑜伽"],
    contraindications: ["急性拉伤部位不要强行拉伸"],
  },
];

export function findExercise(id: string) {
  return exerciseLibrary.find((exercise) => exercise.id === id);
}

export function getExercisesForEnvironment(environment: TrainingEnvironment, equipment: string[]) {
  return exerciseLibrary.filter((exercise) => {
    const fitsEnvironment = exercise.environment === "both" || environment === "both" || exercise.environment === environment;
    const equipmentFits = exercise.equipment.every((item) => equipment.includes(item) || item === "瑜伽垫");
    return fitsEnvironment && equipmentFits;
  });
}
